# Generated by Django 3.2.4 on 2021-06-23 05:50

"""
    - Create model Pizza
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('Regular', 'Regular'), ('Square', 'Square')])),
                ('size', models.TextField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Extra-Large', 'Xl')])),
            ],
        ),
    ]
