# Generated by Django 3.2.4 on 2021-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaAPI', '0002_alter_pizza_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.TextField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Jumbo', 'Jumbo')]),
        ),
    ]
